language: java
jdk: openjdk7

branches:
  only:
    - master

env:
  global:
    # Your Sonatype login
    - SONATYPE_USERNAME=prototik
    # Your Sonatype password, encrypted by 'travis encrypt -r GitHubLogin/Repo SONATYPE_PASSWORD=pass'
    - secure: "EQRmSK6tLEAiE38+yzrbZoMi++dIYU96pHIY5x/L6OtIZTPm8AujXeCiOqL2\n5MFKQ7QPeoWbRbSEh7Ish1q9fD1acUL+x1JywbTJya+DderHTsrbO4LFlehU\nTKyCamiWh9x7eWRX/BZS0hlqDcSAQ1IVGXMIDcydOigvYGI0KcI="

notifications:
  email:
    - prototypegamez@gmail.com

install: python2 .travis.py
script: echo Tests skipped
